export const languages = {
  en: {
    year: 'year',
    years: 'years',
    month: 'month',
    months: 'months',
    day: 'day',
    days: 'days',
    hour: 'hour',
    hours: 'hours',
    minutes: 'minute',
    minutes: 'minutes',
    second: 'second',
    seconds: 'seconds',
    and: 'and',
  },
  es: {
    year: 'año',
    years: 'años',
    month: 'mes',
    months: 'meses',
    day: 'dia',
    days: 'dias',
    hour: 'hora',
    hours: 'horas',
    minute: 'minuto',
    minutes: 'minutos',
    second: 'segundo',
    seconds: 'segundos',
    and: 'y',
  },
};
